# Different Ways to Create Numpy Arrays in Python

### Create Numpy Arrays Using Lists or Tuples

The simplest way to create a NumPy array is by passing a Python list or tuple to the numpy.array() function. This method creates a one-dimensional array.

In [4]:
# One-deminsional array
import numpy as np 
a = np.array([1,3,5,7])
print(a)

[1 3 5 7]


### Initialize a Python NumPy Array Using Special Functions
NumPy provides several built-in functions to generate arrays with specific properties.

- np.zeros(): Creates an array filled with zeros.
- np.ones(): Creates an array filled with ones.
- np.full(): Creates an array filled with a specified value.
- np.arange(): Creates an array with values that are evenly spaced within a given range.
- np.linspace(): Creates an array with values that are evenly spaced over a specified interval.

1. Zero()

In [5]:
import numpy as np 
a = np.zeros(5)  #1D
print("Array:",a)

Array: [0. 0. 0. 0. 0.]


In [12]:
b = np.zeros((2,2), dtype=[('f','f4'),('i','i4')]) #2D
print("Array:\n",b)

Array:
 [[(0., 0) (0., 0)]
 [(0., 0) (0., 0)]]


In [15]:
c = np.zeros([2,2],order='F')
print(c)

[[0. 0.]
 [0. 0.]]


2. Ones() 

The numpy.ones() function returns a new array of given shape and type, with ones.


In [ ]:
arr = np.ones(3) #1D
print("Array1:",arr)

Array1: [1. 1. 1.]


In [ ]:
arr1 = np.ones((3,3),dtype= int) # 2D
print("Array2:\n",arr1)

Array2:
 [[1 1 1]
 [1 1 1]
 [1 1 1]]


In [19]:
arr = np.ones((3,3,3),dtype= int)
print(arr)

[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]


3. np.full()

numpy.full(shape, fill_value, dtype = None, order = 'C') : Return a new array with the same shape and type as a given array filled with a fill_value.

In [24]:
a = np.full((5,5),10)
print(a)

[[10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]]


In [25]:
b = np.full((3,3,2),6,dtype= float)
print(b)

[[[6. 6.]
  [6. 6.]
  [6. 6.]]

 [[6. 6.]
  [6. 6.]
  [6. 6.]]

 [[6. 6.]
  [6. 6.]
  [6. 6.]]]


4. arrange()

numpy.arange() function creates an array of evenly spaced values within a given interval. It is similar to Python's built-in range() function but returns a NumPy array instead of a list.


In [26]:
a = np.arange(5,10)
print(a)

[5 6 7 8 9]


In [34]:
num = np.arange(2,3,0.5)
print(num)

[2.  2.5]


In [35]:
num = np.arange(0,30,3)
seq = num[num > 10]
print(seq)

[12 15 18 21 24 27]


4. linespce()

In [38]:
a = np.linspace(0,1,num=10)
print(a)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]
